### ISSUE TITLE
init the mixin opt with privatekey Buffer error

### ISSUE THREAD

**Issue by caosbad** [virushuo/mixin-node#1]
Try to config mixin node like this
```
{
    client_id: mixin.MIXIN_CLIENT_ID,
    aeskey: mixin.MIXIN_AESKEY,
    pin: mixin.MIXIN_PIN,
    session_id: mixin.MIXIN_SESSION_ID,
    secret: mixin.MIXIN_CLIENT_SECTET,
    privatekey: Buffer.from('-----BEGIN RSA PRIVATE KEY-----  ....   -----END RSA PRIVATE KEY-----'),
  }
```

got error
```
index.js:112
Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
crypto.js:331
    at Sign.sign (crypto.js:331:26)
    at Object.sign (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/jwa/index.js:55:45)
    at Object.jwsSign [as sign] (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/jws/lib/sign-stream.js:23:24)
    at Object.module.exports [as sign] (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/jsonwebtoken/sign.js:189:16)
    at MIXINNODE.self.jwtToken (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/mixin-node/index.js:127:23)
    at MIXINNODE.self.tokenGET (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/mixin-node/index.js:132:17)
    at MIXINNODE.authTokenGET (/Users/caoshuai/develop/workspace/temp/xexServer/node_modules/mixin-node/index.js:223:15)
    at initWs (/Users/caoshuai/develop/workspace/temp/xexServer/app.js:113:17)
    at Object.<anonymous> (/Users/caoshuai/develop/workspace/temp/xexServer/app.js:122:1)
    at Module._compile (module.js:635:30)
```
may be I use the wrong Buffer.from API to convert the  String value.

could you tell the how to config with `PrivateKey(Buffer)` in this way.

**Comment by huo-ju** [comment]
You have to keep the newline character, try ` instead ' or add the '\n' character explicitly.

let key =  Buffer.from(`-----BEGIN RSA PRIVATE KEY-----
.....
-----END RSA PRIVATE KEY-----`);

**Comment by caosbad** [comment]
Thats work , Thx
