### ISSUE TITLE
Mixin 服务器会定期抽风每天有一两次会返回一个 html 的页面而不是JSON。

### ISSUE THREAD

**Issue by Leask** [virushuo/mixin-node#14]
https://github.com/huo-ju/mixin-node/blob/a324cac4add0c8b6908d42e61507c791f4f6a6fe/index.js#L638

这个问题严格来说不是 mixin node 的问题，而是Mixin服务器的问题，这个问题会导致自动化的服务经常会有异常的 log 输出。

我打算把这个优化掉，改为更人性化的报错。我将在使用 node-fetch 替换 request 的工作处理的时候顺便优化这里。

此 issue 仅用做记录，并非需要紧急修正。

```
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at module.exports (/app/node_modules/mixin-node/requestHandler.js:8:20)
    at Request._callback (/app/node_modules/mixin-node/index.js:218:9)
    at Request.self.callback (/app/node_modules/request/request.js:185:22)
    at Request.emit (node:events:329:20)
    at Request.EventEmitter.emit (node:domain:467:12)
    at Request.<anonymous> (/app/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:329:20)
    at Request.EventEmitter.emit (node:domain:467:12)
    at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:435:28)
    at IncomingMessage.emit (node:events:341:22)
    at IncomingMessage.EventEmitter.emit (node:domain:467:12)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

**Comment by Leask** [comment]
指派给我自己，怕到时候忘记了。

**Comment by lxalano** [comment]
优秀
